import { ReactNode, useState } from "react";
import { Plus, Sparkles, User, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";
import ActionItem from "./ActionItem";

interface ActionButton {
  label: string;
  variant?: "default" | "outline" | "secondary";
  onClick?: () => void;
}

interface ActionItemData {
  id: string;
  title: string;
  severity?: "critical" | "high" | "medium" | "low";
  status?: string;
  statusVariant?: "default" | "success" | "warning" | "danger";
  description?: string | ReactNode;
  issues?: string[];
  actions?: ActionButton[];
}

interface ManualActionItem {
  id: string;
  text: string;
  completed: boolean;
}

interface ActionItemsSectionProps {
  autoGeneratedItems: ActionItemData[];
  initialManualItems?: ManualActionItem[];
  onManualItemsChange?: (items: ManualActionItem[]) => void;
  className?: string;
}

const ActionItemsSection = ({
  autoGeneratedItems,
  initialManualItems = [],
  onManualItemsChange,
  className,
}: ActionItemsSectionProps) => {
  const [manualItems, setManualItems] = useState<ManualActionItem[]>(initialManualItems);
  const [newItemText, setNewItemText] = useState("");
  const [isAddingItem, setIsAddingItem] = useState(false);

  const addManualItem = () => {
    if (!newItemText.trim()) return;
    
    const newItem: ManualActionItem = {
      id: `manual-${Date.now()}`,
      text: newItemText.trim(),
      completed: false,
    };
    
    const updatedItems = [...manualItems, newItem];
    setManualItems(updatedItems);
    onManualItemsChange?.(updatedItems);
    setNewItemText("");
    setIsAddingItem(false);
  };

  const toggleItemComplete = (id: string) => {
    const updatedItems = manualItems.map(item =>
      item.id === id ? { ...item, completed: !item.completed } : item
    );
    setManualItems(updatedItems);
    onManualItemsChange?.(updatedItems);
  };

  const removeManualItem = (id: string) => {
    const updatedItems = manualItems.filter(item => item.id !== id);
    setManualItems(updatedItems);
    onManualItemsChange?.(updatedItems);
  };

  return (
    <div className={cn("space-y-6", className)}>
      {/* Auto-Generated Action Items */}
      <div>
        <div className="flex items-center gap-2 mb-4">
          <div className="p-1.5 rounded-md bg-purple-100">
            <Sparkles className="w-4 h-4 text-purple-600" />
          </div>
          <h3 className="font-semibold text-foreground">Auto-Generated Actions</h3>
          <Badge variant="secondary" className="text-xs">
            {autoGeneratedItems.length} items
          </Badge>
        </div>
        
        {autoGeneratedItems.length > 0 ? (
          <div className="space-y-4">
            {autoGeneratedItems.map((item) => (
              <ActionItem
                key={item.id}
                title={item.title}
                severity={item.severity}
                status={item.status}
                statusVariant={item.statusVariant}
                description={item.description}
                issues={item.issues}
                actions={item.actions}
              />
            ))}
          </div>
        ) : (
          <div className="p-6 rounded-xl border border-dashed border-green-200 bg-green-50/50 text-center">
            <p className="text-sm text-green-700">
              ✓ No auto-generated action items. All systems operating normally.
            </p>
          </div>
        )}
      </div>

      {/* Manual Action Items */}
      <div>
        <div className="flex items-center justify-between mb-4">
          <div className="flex items-center gap-2">
            <div className="p-1.5 rounded-md bg-blue-100">
              <User className="w-4 h-4 text-blue-600" />
            </div>
            <h3 className="font-semibold text-foreground">Manual Action Items</h3>
            <Badge variant="secondary" className="text-xs">
              {manualItems.filter(i => !i.completed).length} pending
            </Badge>
          </div>
          
          {!isAddingItem && (
            <Button
              size="sm"
              variant="outline"
              onClick={() => setIsAddingItem(true)}
              className="gap-1"
            >
              <Plus className="w-4 h-4" />
              Add Item
            </Button>
          )}
        </div>

        {/* Add new item form */}
        {isAddingItem && (
          <div className="flex gap-2 mb-4">
            <Input
              placeholder="Enter action item..."
              value={newItemText}
              onChange={(e) => setNewItemText(e.target.value)}
              onKeyDown={(e) => e.key === "Enter" && addManualItem()}
              autoFocus
              className="flex-1"
            />
            <Button size="sm" onClick={addManualItem}>
              Add
            </Button>
            <Button 
              size="sm" 
              variant="ghost" 
              onClick={() => {
                setIsAddingItem(false);
                setNewItemText("");
              }}
            >
              Cancel
            </Button>
          </div>
        )}

        {/* Manual items list */}
        {manualItems.length > 0 ? (
          <div className="space-y-2">
            {manualItems.map((item) => (
              <div
                key={item.id}
                className={cn(
                  "flex items-center gap-3 p-3 rounded-lg border bg-card transition-all",
                  item.completed && "opacity-60 bg-muted/50"
                )}
              >
                <button
                  onClick={() => toggleItemComplete(item.id)}
                  className={cn(
                    "w-5 h-5 rounded border-2 flex items-center justify-center transition-colors",
                    item.completed
                      ? "bg-green-500 border-green-500 text-white"
                      : "border-muted-foreground/30 hover:border-primary"
                  )}
                >
                  {item.completed && (
                    <svg className="w-3 h-3" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                    </svg>
                  )}
                </button>
                <span className={cn(
                  "flex-1 text-sm",
                  item.completed && "line-through text-muted-foreground"
                )}>
                  {item.text}
                </span>
                <button
                  onClick={() => removeManualItem(item.id)}
                  className="p-1 rounded hover:bg-destructive/10 text-muted-foreground hover:text-destructive transition-colors"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>
            ))}
          </div>
        ) : (
          <div className="p-6 rounded-xl border border-dashed border-muted-foreground/20 bg-muted/20 text-center">
            <p className="text-sm text-muted-foreground">
              No manual action items yet. Click "Add Item" to create one.
            </p>
          </div>
        )}
      </div>
    </div>
  );
};

export default ActionItemsSection;